"""artifact store metadata

Revision ID: 1cfd55439fd3
Revises: 9a56191f3f4c
Create Date: 2026-08-12 11:18:13.814389
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1cfd55439fd3'
down_revision: Union[str, None] = '9a56191f3f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('object_key', sa.String(length=512), nullable=True))
    op.add_column('artifacts', sa.Column('content_type', sa.String(length=128), nullable=False))
    op.add_column('artifacts', sa.Column('store_name', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts', 'store_name')
    op.drop_column('artifacts', 'content_type')
    op.drop_column('artifacts', 'object_key')
    # ### end Alembic commands ###
