"""initial schema

Revision ID: 572b9ffa9375
Revises: 
Create Date: 2026-08-12 08:40:05.052169
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '572b9ffa9375'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_workspace_id'), 'artifacts', ['workspace_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('robot_type', sa.String(length=64), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('edge_agent_id', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_edge_agent_id'), 'deployments', ['edge_agent_id'], unique=False)
    op.create_index(op.f('ix_deployments_workspace_id'), 'deployments', ['workspace_id'], unique=False)
    op.create_table('edge_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('gpu_hosts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_organizations_owner', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streaming_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('signal_port', sa.Integer(), nullable=True),
    sa.Column('media_port', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaming_sessions_workspace_id'), 'streaming_sessions', ['workspace_id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('edge_agent_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_edge_agent_id'), 'telemetry_events', ['edge_agent_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('runtime', sa.String(length=32), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('gpu_requirement_gb', sa.Integer(), nullable=False),
    sa.Column('repo_asset', sa.Text(), nullable=True),
    sa.Column('entrypoint', sa.Text(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('requires_streaming', sa.Boolean(), nullable=False),
    sa.Column('healthcheck', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('launch_command', sa.Text(), nullable=False),
    sa.Column('recommended_vram_gb', sa.Integer(), nullable=False),
    sa.Column('estimated_hourly_cost_cny', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_slug'), 'templates', ['slug'], unique=True)
    op.create_table('gpus',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gpu_uuid', sa.String(length=128), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('memory_total', sa.Integer(), nullable=False),
    sa.Column('gpu_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['gpu_hosts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gpu_uuid'),
    sa.UniqueConstraint('workspace_id', name='uq_gpus_workspace')
    )
    op.create_index(op.f('ix_gpus_host_id'), 'gpus', ['host_id'], unique=False)
    op.create_index('ix_gpus_status', 'gpus', ['status'], unique=False)
    op.create_index(op.f('ix_gpus_workspace_id'), 'gpus', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_courses_organization_id'), 'courses', ['organization_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('gpu_seconds', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_credit_ledger_organization_id'), 'credit_ledger', ['organization_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_type'), 'credit_ledger', ['type'], unique=False)
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_workspace_id'), 'credit_ledger', ['workspace_id'], unique=False)
    op.create_index('ix_ledger_user_created', 'credit_ledger', ['user_id', 'created_at'], unique=False)
    op.create_table('gpu_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gpu_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gpu_id')
    )
    op.create_index(op.f('ix_gpu_allocations_host_id'), 'gpu_allocations', ['host_id'], unique=False)
    op.create_index(op.f('ix_gpu_allocations_workspace_id'), 'gpu_allocations', ['workspace_id'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('gpu_index', sa.Integer(), nullable=True),
    sa.Column('gpu_name', sa.String(length=120), nullable=True),
    sa.Column('gpu_id', sa.String(length=36), nullable=True),
    sa.Column('ide_port', sa.Integer(), nullable=True),
    sa.Column('signal_port', sa.Integer(), nullable=True),
    sa.Column('media_port', sa.Integer(), nullable=True),
    sa.Column('ide_url', sa.Text(), nullable=True),
    sa.Column('stream_hint', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('container_name', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accumulated_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_organization_id'), 'workspaces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workspaces_template_id'), 'workspaces', ['template_id'], unique=False)
    op.create_index(op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False)
    op.create_table('course_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_member')
    )
    op.create_index(op.f('ix_course_members_course_id'), 'course_members', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_members_user_id'), 'course_members', ['user_id'], unique=False)
    op.create_table('labs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quota_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_course_id'), 'labs', ['course_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lab_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_lab_id'), 'assignments', ['lab_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'user_id', name='uq_submission_user')
    )
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_assignments_lab_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_labs_course_id'), table_name='labs')
    op.drop_table('labs')
    op.drop_index(op.f('ix_course_members_user_id'), table_name='course_members')
    op.drop_index(op.f('ix_course_members_course_id'), table_name='course_members')
    op.drop_table('course_members')
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_template_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_organization_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_gpu_allocations_workspace_id'), table_name='gpu_allocations')
    op.drop_index(op.f('ix_gpu_allocations_host_id'), table_name='gpu_allocations')
    op.drop_table('gpu_allocations')
    op.drop_index('ix_ledger_user_created', table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_workspace_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_type'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_organization_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_courses_organization_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_gpus_workspace_id'), table_name='gpus')
    op.drop_index('ix_gpus_status', table_name='gpus')
    op.drop_index(op.f('ix_gpus_host_id'), table_name='gpus')
    op.drop_table('gpus')
    op.drop_index(op.f('ix_templates_slug'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_telemetry_events_edge_agent_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_streaming_sessions_workspace_id'), table_name='streaming_sessions')
    op.drop_table('streaming_sessions')
    op.drop_table('organizations')
    op.drop_table('gpu_hosts')
    op.drop_table('edge_agents')
    op.drop_index(op.f('ix_deployments_workspace_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_edge_agent_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_artifacts_workspace_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
