"""active operation uniqueness

Revision ID: 87c6c7d2d168
Revises: c7c6f510d21f
Create Date: 2026-08-12 12:11:10.729804
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87c6c7d2d168'
down_revision: Union[str, None] = 'c7c6f510d21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 不支持 ALTER 加 FK（models 的 FK 由 PostgreSQL 原生支持）
    op.create_index('uq_ops_active_per_workspace', 'workspace_operations', ['workspace_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'running', 'retrying')"), postgresql_where=sa.text("status IN ('pending', 'running', 'retrying')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ops_active_per_workspace', table_name='workspace_operations', sqlite_where=sa.text("status IN ('pending', 'running', 'retrying')"), postgresql_where=sa.text("status IN ('pending', 'running', 'retrying')"))
    # ### end Alembic commands ###
