"""template current version pointer

Revision ID: 93cc4735342a
Revises: 1cfd55439fd3
Create Date: 2026-08-12 11:23:08.297910
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93cc4735342a'
down_revision: Union[str, None] = '1cfd55439fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('current_version_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'current_version_id')
    # ### end Alembic commands ###
