"""operation lease fencing

Revision ID: 9a56191f3f4c
Revises: bf8d0efb276f
Create Date: 2026-08-12 10:55:13.983836
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a56191f3f4c'
down_revision: Union[str, None] = 'bf8d0efb276f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_operations', sa.Column('lease_owner', sa.String(length=64), nullable=True))
    op.add_column('workspace_operations', sa.Column('fencing_token', sa.String(length=64), nullable=True))
    op.add_column('workspace_operations', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_operations', 'heartbeat_at')
    op.drop_column('workspace_operations', 'fencing_token')
    op.drop_column('workspace_operations', 'lease_owner')
    # ### end Alembic commands ###
