"""workspace operations table

Revision ID: a359de4e4d50
Revises: 572b9ffa9375
Create Date: 2026-08-12 09:37:57.247110
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a359de4e4d50'
down_revision: Union[str, None] = '572b9ffa9375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ops_status_lease', 'workspace_operations', ['status', 'lease_expires_at'], unique=False)
    op.create_index('ix_ops_workspace_status', 'workspace_operations', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_workspace_operations_operation_type'), 'workspace_operations', ['operation_type'], unique=False)
    op.create_index(op.f('ix_workspace_operations_status'), 'workspace_operations', ['status'], unique=False)
    op.create_index(op.f('ix_workspace_operations_workspace_id'), 'workspace_operations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_operations_workspace_id'), table_name='workspace_operations')
    op.drop_index(op.f('ix_workspace_operations_status'), table_name='workspace_operations')
    op.drop_index(op.f('ix_workspace_operations_operation_type'), table_name='workspace_operations')
    op.drop_index('ix_ops_workspace_status', table_name='workspace_operations')
    op.drop_index('ix_ops_status_lease', table_name='workspace_operations')
    op.drop_table('workspace_operations')
    # ### end Alembic commands ###
