"""warm pool state

Revision ID: bf8d0efb276f
Revises: d19abc033347
Create Date: 2026-08-12 10:17:35.661288
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf8d0efb276f'
down_revision: Union[str, None] = 'd19abc033347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('warm_pool_state', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_workspaces_warm_pool_state'), 'workspaces', ['warm_pool_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_warm_pool_state'), table_name='workspaces')
    op.drop_column('workspaces', 'warm_pool_state')
    # ### end Alembic commands ###
