"""edge agent tenant ownership

Revision ID: c7c6f510d21f
Revises: 93cc4735342a
Create Date: 2026-08-12 11:56:06.835484
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c7c6f510d21f'
down_revision: Union[str, None] = '93cc4735342a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edge_agents', sa.Column('owner_user_id', sa.String(length=36), nullable=True))
    op.add_column('edge_agents', sa.Column('organization_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_edge_agents_organization_id'), 'edge_agents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_edge_agents_owner_user_id'), 'edge_agents', ['owner_user_id'], unique=False)
    # SQLite 不支持 ALTER 加 FK（batch mode 才可）；FK 关系见 models 定义，
    # PostgreSQL 由 autogenerate 原生支持；SQLite 开发库以应用层校验为主。
    # 数据库级 FK 约束将在 Data Integrity 阶段统一 batch 处理。
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edge_agents_owner_user_id'), table_name='edge_agents')
    op.drop_index(op.f('ix_edge_agents_organization_id'), table_name='edge_agents')
    op.drop_column('edge_agents', 'organization_id')
    op.drop_column('edge_agents', 'owner_user_id')
    # ### end Alembic commands ###
