"""immutable template versions

Revision ID: d19abc033347
Revises: eacad364347f
Create Date: 2026-08-12 09:55:41.655428
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd19abc033347'
down_revision: Union[str, None] = 'eacad364347f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('image_digest', sa.String(length=128), nullable=True),
    sa.Column('entrypoint', sa.Text(), nullable=False),
    sa.Column('gpu_requirement_gb', sa.Integer(), nullable=False),
    sa.Column('requires_streaming', sa.Boolean(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('healthcheck', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('source_revision', sa.String(length=128), nullable=True),
    sa.Column('released', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_template_version')
    )
    op.create_index('ix_template_versions_template_id', 'template_versions', ['template_id'], unique=False)
    op.add_column('workspaces', sa.Column('template_version_id', sa.String(length=36), nullable=True))
    op.add_column('workspaces', sa.Column('image', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_workspaces_template_version_id'), 'workspaces', ['template_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_template_version_id'), table_name='workspaces')
    op.drop_column('workspaces', 'image')
    op.drop_column('workspaces', 'template_version_id')
    op.drop_index('ix_template_versions_template_id', table_name='template_versions')
    op.drop_table('template_versions')
    # ### end Alembic commands ###
