"""workspace soft delete tombstone

Revision ID: eacad364347f
Revises: a359de4e4d50
Create Date: 2026-08-12 09:53:29.792756
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eacad364347f'
down_revision: Union[str, None] = 'a359de4e4d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_workspaces_deleted_at'), 'workspaces', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_deleted_at'), table_name='workspaces')
    op.drop_column('workspaces', 'deleted_at')
    # ### end Alembic commands ###
